// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicat]ng the section will prevent
// it from being updated in th future.
#include "Shift.h"
Shift::Shift()
: on(false)
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shifter);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void Shift::Initialize() {
			if(on)
			{
				Robot::shifter->shifter->Set(DoubleSolenoid::kReverse);
				on = false;
			}
			else
			{
				Robot::shifter->shifter->Set(DoubleSolenoid::kForward);
				on = true;
			}
/*				Old Non-working Stuff
	if(Robot::shifter->shifter->Get()==DoubleSolenoid::kReverse);
		{
			Robot::shifter->shifter->Set(DoubleSolenoid::kForward);
		}
			
	else if(Robot::shifter->shifter->Get()==DoubleSolenoid::kForward);
		{				
			Robot::shifter->shifter->Set(DoubleSolenoid::kReverse);
		}
*/	
}
// Called repeatedly when this Command is scheduled to run
void Shift::Execute() {
}
// Make this return true when this Command no longer needs to run execute()
bool Shift::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void Shift::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Shift::Interrupted() {
}
