// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* coDriver;
	JoystickButton* cLeftBumper;
	JoystickButton* cButtonBack;
	JoystickButton* cButtonStart;
	JoystickButton* cRightBumper;
	JoystickButton* cButtonY;
	JoystickButton* cButtonB;
	Joystick* driver;
	JoystickButton* dLeftStick;
	JoystickButton* dRightBumper;
	JoystickButton* dButtonX;
	JoystickButton* dButtonA;
	JoystickButton* dButtonY;
	JoystickButton* dButtonB;
	JoystickButton* dRightStick;
	JoystickButton* dButtonBack;
	JoystickButton* dButtonStart;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	Joystick* getdriver();
	Joystick* getcoDriver();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};
#endif
