// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::intakeIntake = NULL;
DoubleSolenoid* RobotMap::intakeSpoiler = NULL;
CANJaguar* RobotMap::conveyorConveyor = NULL;
DoubleSolenoid* RobotMap::conveyorStopper = NULL;
CANJaguar* RobotMap::shooterShooterA = NULL;
CANJaguar* RobotMap::shooterShooterB = NULL;
CANJaguar* RobotMap::chassisFrontLeft = NULL;
CANJaguar* RobotMap::chassisFrontRight = NULL;
CANJaguar* RobotMap::chassisBackLeft = NULL;
CANJaguar* RobotMap::chassisBackRight = NULL;
RobotDrive* RobotMap::chassisRobotDrive = NULL;
DoubleSolenoid* RobotMap::shifterShifter = NULL;
DigitalInput* RobotMap::sensorslightSensor = NULL;
CANJaguar* RobotMap::armArmA = NULL;
CANJaguar* RobotMap::armArmB = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	intakeIntake = new CANJaguar(11);
	
	
	intakeSpoiler = new DoubleSolenoid(0, 4, 6);
	
	
	conveyorConveyor = new CANJaguar(12);
	
	
	conveyorStopper = new DoubleSolenoid(0, 1, 3);
	
	
	shooterShooterA = new CANJaguar(7);
	
	
	shooterShooterB = new CANJaguar(8);
	
	
	chassisFrontLeft = new CANJaguar(2);
	
	
	chassisFrontRight = new CANJaguar(4);
	
	
	chassisBackLeft = new CANJaguar(3);
	
	
	chassisBackRight = new CANJaguar(5);
	
	
	chassisRobotDrive = new RobotDrive(chassisFrontLeft, chassisBackLeft,
              chassisFrontRight, chassisBackRight);
	
	chassisRobotDrive->SetSafetyEnabled(true);
        chassisRobotDrive->SetExpiration(0.1);
        chassisRobotDrive->SetSensitivity(0.5);
        chassisRobotDrive->SetMaxOutput(1.0);
	shifterShifter = new DoubleSolenoid(0, 7, 5);
	
	
	sensorslightSensor = new DigitalInput(8);
	lw->AddSensor("Sensors", "lightSensor", sensorslightSensor);
	
	armArmA = new CANJaguar(9);
	
	
	armArmB = new CANJaguar(10);
	
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
